USE mydoc_db;

ALTER TABLE tblCustomer
  MODIFY COLUMN CustomerID VARCHAR(6) NOT NULL,
  MODIFY COLUMN IDTerm VARCHAR(6) NULL;

ALTER TABLE tblProduct
  MODIFY COLUMN ProductID VARCHAR(6) NOT NULL;

ALTER TABLE tblDestination
  MODIFY COLUMN DestID VARCHAR(6) NOT NULL;

ALTER TABLE tblPaymentTerm
  MODIFY COLUMN TermID VARCHAR(6) NOT NULL;

ALTER TABLE tblMonitor
  MODIFY COLUMN CustomerID VARCHAR(6) NULL,
  MODIFY COLUMN TermID VARCHAR(6) NULL,
  MODIFY COLUMN DestinationID VARCHAR(6) NULL;

ALTER TABLE tblMonitorDetail
  MODIFY COLUMN ProductID VARCHAR(6) NOT NULL;